# Generated by Django 5.0.4 on 2024-04-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='VideoSubtitle',
            fields=[
                ('subtitle_text_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='字幕テキストID')),
                ('subtitle_id', models.CharField(max_length=50, verbose_name='字幕ID')),
                ('t_start_ms', models.IntegerField(blank=True, null=True, verbose_name='開始時間（ミリ秒）')),
                ('d_duration_ms', models.IntegerField(blank=True, null=True, verbose_name='持続時間（ミリ秒）')),
                ('t_offset_ms', models.IntegerField(blank=True, null=True, verbose_name='オフセット時間（ミリ秒）')),
                ('subtitle_text', models.TextField(verbose_name='字幕')),
            ],
            options={
                'db_table': 'video_subtitle',
            },
        ),
        migrations.CreateModel(
            name='VideoSubtitleInfo',
            fields=[
                ('subtitle_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='字幕ID')),
                ('video_id', models.CharField(max_length=50, verbose_name='動画ID')),
                ('subtitle_type', models.IntegerField(verbose_name='自動/手動')),
                ('language_code', models.CharField(max_length=10, verbose_name='言語コード')),
                ('has_subtitle', models.BooleanField(verbose_name='字幕があるかないか')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考欄')),
            ],
            options={
                'db_table': 'video_subtitle_info',
                'unique_together': {('video_id', 'subtitle_type', 'language_code')},
            },
        ),
    ]
