# Generated by Django 5.0.4 on 2024-04-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSubtitleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50, verbose_name='動画ID')),
                ('subtitle_type', models.CharField(max_length=10, verbose_name='自動/手動')),
                ('language_code', models.CharField(max_length=10, verbose_name='言語コード')),
                ('has_subtitle', models.BooleanField(verbose_name='字幕があるかないか')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考欄')),
            ],
            options={
                'db_table': 'video_subtitle_info',
            },
        ),
    ]
