# Generated by Django 5.0.4 on 2024-04-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosubtitleinfo',
            name='language_code',
            field=models.CharField(choices=[('ja', 'JAPANESE'), ('en', 'ENGLISH'), ('ko', 'KOREAN'), ('zh', 'CHINESE'), ('id', 'INDONESIAN')], verbose_name='言語コード'),
        ),
        migrations.AlterField(
            model_name='videosubtitleinfo',
            name='subtitle_type',
            field=models.IntegerField(choices=[(0, 'AUTOMATIC'), (1, 'MANUAL')], verbose_name='字幕の種類'),
        ),
    ]
