# Generated by Django 5.0.4 on 2024-05-01 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0002_alter_videosubtitleinfo_language_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSubtitleDetail',
            fields=[
                ('subtitle_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                                    related_name='subtitle', serialize=False, to='myapp.videosubtitle',
                                                    verbose_name='字幕テキストID')),
                ('subtitle_transration_text', models.TextField(verbose_name='字幕')),
                ('subtitle_transration_text_detail', models.TextField(verbose_name='字幕')),
            ],
            options={
                'db_table': 'video_subtitle_detail',
            },
        ),
    ]
