# Generated by Django 5.0.4 on 2024-04-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_videosubtitleinfo_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50, verbose_name='動画ID')),
                ('subtitle_type', models.CharField(max_length=10, verbose_name='自動/手動')),
                ('language_code', models.CharField(max_length=10, verbose_name='言語コード')),
                ('t_start_ms', models.IntegerField(verbose_name='開始時間（ミリ秒）')),
                ('d_duration_ms', models.IntegerField(verbose_name='持続時間（ミリ秒）')),
                ('t_offset_ms', models.IntegerField(verbose_name='オフセット時間（ミリ秒）')),
                ('subtitle_text', models.TextField(verbose_name='字幕')),
            ],
            options={
                'db_table': 'video_subtitle',
            },
        ),
    ]
