# Generated by Django 5.0.4 on 2024-05-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_videosubtitledetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosubtitledetail',
            name='subtitle_transration_text',
            field=models.TextField(blank=True, null=True, verbose_name='翻訳字幕'),
        ),
        migrations.AlterField(
            model_name='videosubtitledetail',
            name='subtitle_transration_text_detail',
            field=models.TextField(blank=True, null=True, verbose_name='翻訳字幕詳細'),
        ),
    ]
