# Generated by Django 5.0.4 on 2024-04-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_videosubtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosubtitle',
            name='d_duration_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='持続時間（ミリ秒）'),
        ),
        migrations.AlterField(
            model_name='videosubtitle',
            name='t_offset_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='オフセット時間（ミリ秒）'),
        ),
        migrations.AlterField(
            model_name='videosubtitle',
            name='t_start_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='開始時間（ミリ秒）'),
        ),
    ]
