# Generated by Django 5.0.4 on 2024-05-01 10:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_videosubtitledetail_subtitle_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelDetail',
            fields=[
                ('channel_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='チャンネルID')),
                ('channel_playlist_id', models.CharField(max_length=50, verbose_name='チャンネルプレイリストID')),
                ('default_audio_language', models.CharField(choices=[('ja', 'JAPANESE'), ('en', 'ENGLISH'), ('ko', 'KOREAN'), ('zh', 'CHINESE'), ('id', 'INDONESIAN')], verbose_name='言語コード')),
            ],
            options={
                'db_table': 'channel_detail',
            },
        ),
        migrations.RemoveField(
            model_name='videosubtitledetail',
            name='subtitle_text_id',
        ),
        migrations.RemoveField(
            model_name='videosubtitleinfo',
            name='video_id',
        ),
        migrations.AddField(
            model_name='videosubtitledetail',
            name='subtitle_text',
            field=models.OneToOneField(default=datetime.datetime(2024, 5, 1, 10, 32, 0, 206265, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='video_subtitle', serialize=False, to='myapp.videosubtitle', verbose_name='字幕テキストID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videosubtitle',
            name='subtitle_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_subtitle_info', to='myapp.videosubtitleinfo', verbose_name='字幕ID'),
        ),
        migrations.AddField(
            model_name='videosubtitleinfo',
            name='video',
            field=models.ForeignKey(default=datetime.datetime(2024, 5, 1, 10, 32, 4, 748058, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, related_name='video_detail', to='myapp.channeldetail', verbose_name='動画ID'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VideoDetail',
            fields=[
                ('video_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='動画ID')),
                ('is_disabled', models.BooleanField(verbose_name='削除フラグ')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_detail', to='myapp.channeldetail', verbose_name='チャンネルID')),
            ],
            options={
                'db_table': 'video_detail',
            },
        ),
    ]
