# Generated by Django 5.0.4 on 2024-04-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_videosubtitle_d_duration_ms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosubtitle',
            name='subtitle_type',
            field=models.IntegerField(verbose_name='自動/手動'),
        ),
        migrations.AlterField(
            model_name='videosubtitleinfo',
            name='subtitle_type',
            field=models.IntegerField(verbose_name='自動/手動'),
        ),
    ]
