# Generated by Django 5.0.4 on 2024-05-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_channeldetail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videosubtitleinfo',
            old_name='subtitle_id',
            new_name='subtitle_info_id',
        ),
    ]
