# Generated by Django 5.0.4 on 2024-05-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_channellocalized_channel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetail',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
    ]
