# Generated by Django 5.0.4 on 2024-05-01 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0016_subtitletranslation_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subtitletranslation',
            table='subtitle_translation',
        ),
    ]
