# Generated by Django 5.0.4 on 2024-05-04 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0019_alter_videosubtitleinfo_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosubtitleinfo',
            name='has_subtitle',
        ),
    ]
