# Generated by Django 5.0.4 on 2024-05-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0021_alter_channeltranslationinfo_default_audio_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodetail',
            name='initial_flag',
            field=models.BooleanField(default=False, verbose_name='初期登録フラグ'),
        ),
        migrations.AlterField(
            model_name='videosubtitleinfo',
            name='subtitle_status',
            field=models.IntegerField(
                choices=[(0, 'NO_SUBTITLE'), (1, 'REGISTERED'), (2, 'UNREGISTERED'), (3, 'REGISTRATION_FAILED')],
                verbose_name='字幕ステータス'),
        ),
    ]
