# Generated by Django 5.0.4 on 2024-05-10 05:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0023_alter_channellocalized_channel_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtitletranslation',
            old_name='subtitle_transration_text',
            new_name='subtitle_translation_text',
        ),
        migrations.RenameField(
            model_name='subtitletranslation',
            old_name='subtitle_transration_text_detail',
            new_name='subtitle_translation_text_detail',
        ),
    ]
