# Generated by Django 5.0.4 on 2024-05-17 09:36

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0024_rename_subtitle_transration_text_subtitletranslation_subtitle_translation_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitletranslation',
            name='id',
        ),
        migrations.AddField(
            model_name='subtitletranslation',
            name='subtitle_translation_text_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False,
                                   verbose_name='字幕翻訳テキストID'),
        ),
    ]
