# Generated by Django 5.0.4 on 2024-05-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_subtitletranslation_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subtitletranslation',
            unique_together={('subtitle_text_id', 'language_code')},
        ),
    ]
