# Generated by Django 5.0.4 on 2024-05-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0026_alter_subtitletranslation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channeldetail',
            name='country',
            field=models.CharField(max_length=50, null=True, verbose_name='国コード'),
        ),
    ]
