# Generated by Django 5.0.4 on 2024-05-24 05:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0030_alter_subtitlelearningmemory_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitlelearningmemory',
            name='id',
        ),
        migrations.AddField(
            model_name='subtitlelearningmemory',
            name='subtitle_learning_memory_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False,
                                   verbose_name='字幕学習記録ID'),
        ),
    ]
