# Generated by Django 5.0.4 on 2024-07-05 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitlelearningmemory',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', default='test_onigiri', on_delete=django.db.models.deletion.CASCADE, to='myapp.userdata', verbose_name='ユーザーID'),
            preserve_default=False,
        ),
    ]
