# Generated by Django 5.0.4 on 2024-07-05 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_subtitlelearningmemory_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subtitlelearningmemory',
            unique_together={('subtitle_translation_text_id', 'user_id')},
        ),
    ]
