# Generated by Django 5.0.4 on 2024-07-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_baselanguage_learninglanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselanguage',
            name='last_updated',
            field=models.DateTimeField(null=True, verbose_name='最終更新日時'),
        ),
        migrations.AddField(
            model_name='learninglanguage',
            name='last_updated',
            field=models.DateTimeField(null=True, verbose_name='最終更新日時'),
        ),
    ]
